name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images directory (if exists)
        run: if [[ -d mission_statement/images ]]; then cp -R mission_statement/images build/images; fi

      - name: Download moj theme
        run: wget https://github.com/ministryofjustice/marp-moj-theme/blob/main/themes/moj.css

      - name: Get changed mission statement
        id: changed-mission-statement
        uses: tj-actions/changed-files@v44
        with:
          files: mission_statement/README.md

      - name: Marp Build (README)
        if: steps.changed-mission-statement.outputs.any_changed == 'true'
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: mission_statement/README.md -o build/index.html --theme moj.css --html
        env:
          MARP_USER: root:root

      - name: Deploy production
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/