name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images directory (if exists)
        run: if [[ -d mission_statement/images ]]; then cp -R mission_statement/images build/images; fi

      - name: Download moj theme
        run: wget https://raw.githubusercontent.com/ministryofjustice/marp-moj-theme/main/themes/moj.css

      - name: Get changed mission statement
        id: changed-mission-statement
        uses: tj-actions/changed-files@v44
        with:
          files: mission_statement/README.md

      - name: Marp Build (README)
        # if: steps.changed-mission-statement.outputs.any_changed == 'true'
        run: |
          npx @marp-team/marp-cli@latest slide-deck.md mission_statement/README.md \
          -o build/index.html --theme moj.css --html
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
